/**
 * VELORA ESTATES - Fictional Property Dataset (12 Properties)
 * Pure JavaScript Data Model
 */

const PROPERTIES_DATA = [
  {
    id: "prop-01",
    name: "The Meridian Residence",
    tagline: "Ultra-luxury corner residence with panoramic city skyline views.",
    location: "Alipore, Kolkata",
    city: "Kolkata",
    price: "₹3.85 Cr",
    priceValue: 38500000,
    type: "Apartment",
    bedrooms: 4,
    bathrooms: 4,
    area: 3240,
    areaUnit: "sq.ft.",
    status: "Featured",
    featured: true,
    yearBuilt: 2024,
    parking: "2 Covered Spaces",
    description: "The Meridian Residence stands as a benchmark of modern architectural excellence in Alipore. Designed around natural illumination and floor-to-ceiling glass, this 4-bedroom home offers double-height living rooms, imported Italian marble, and private elevator access.",
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=1200&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?q=80&w=1200&auto=format&fit=crop"
    ],
    amenities: ["Private Terrace", "Swimming Pool", "24/7 Security", "Fitness Center", "Covered Parking", "Smart Home Automation", "Concierge Service", "Landscaped Garden"],
    agentId: "agent-01"
  },
  {
    id: "prop-02",
    name: "The Aurelia House",
    tagline: "A private contemporary estate designed around light and landscape.",
    location: "Alipore, Kolkata",
    city: "Kolkata",
    price: "₹8.75 Cr",
    priceValue: 87500000,
    type: "Villa",
    bedrooms: 5,
    bathrooms: 6,
    area: 5800,
    areaUnit: "sq.ft.",
    status: "Signature",
    featured: true,
    yearBuilt: 2025,
    parking: "4 Covered Spaces",
    description: "Aurelia House represents Velora's flagship residential villa in Kolkata's most prestigious enclave. Featuring a 50ft private infinity lap pool, internal glass courtyard, temperature-controlled wine room, and separate staff quarters.",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?q=80&w=1200&auto=format&fit=crop"
    ],
    amenities: ["Private Infinity Pool", "Internal Courtyard", "Wine Cellar", "Smart Home Automation", "Private Security Detail", "Home Theater", "4-Car Garage", "Staff Quarters"],
    agentId: "agent-01"
  },
  {
    id: "prop-03",
    name: "Solara Heights",
    tagline: "Sleek modern high-rise living near Rajarhat IT corridor.",
    location: "New Town, Kolkata",
    city: "Kolkata",
    price: "₹2.15 Cr",
    priceValue: 21500000,
    type: "Apartment",
    bedrooms: 3,
    bathrooms: 3,
    area: 2450,
    areaUnit: "sq.ft.",
    status: "New Listing",
    featured: false,
    yearBuilt: 2023,
    parking: "2 Covered Spaces",
    description: "Solara Heights brings eco-conscious luxury to New Town Kolkata. Outfitted with VRV air conditioning, expansive wrap-around balconies, and access to a 20,000 sq.ft clubhouse.",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=1200&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600566752355-35792bedcfea?q=80&w=1200&auto=format&fit=crop"
    ],
    amenities: ["Rooftop Sky Lounge", "Clubhouse", "Swimming Pool", "24/7 Security", "Power Backup", "EV Charging Point"],
    agentId: "agent-02"
  },
  {
    id: "prop-04",
    name: "Casa Verde",
    tagline: "Tranquil Portuguese-style luxury sanctuary amidst coconut groves.",
    location: "North Goa, Goa",
    city: "Goa",
    price: "₹5.40 Cr",
    priceValue: 54000000,
    type: "Villa",
    bedrooms: 4,
    bathrooms: 5,
    area: 4200,
    areaUnit: "sq.ft.",
    status: "For Sale",
    featured: true,
    yearBuilt: 2024,
    parking: "3 Spaces",
    description: "Nestled in the serene backwaters of Assagao, Casa Verde blends Indo-Portuguese heritage details with minimalist Scandinavian interiors. Features a private plunge pool and verandas.",
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=1200&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600585152220-90363fe7e115?q=80&w=1200&auto=format&fit=crop"
    ],
    amenities: ["Private Plunge Pool", "Veranda", "Tropical Garden", "Gated Security", "Solar Power System", "Fully Furnished"],
    agentId: "agent-03"
  },
  {
    id: "prop-05",
    name: "The Aria Penthouse",
    tagline: "Iconic Arabian Sea view duplex penthouse above Pali Hill.",
    location: "Bandra, Mumbai",
    city: "Mumbai",
    price: "₹9.20 Cr",
    priceValue: 92000000,
    type: "Penthouse",
    bedrooms: 4,
    bathrooms: 5,
    area: 4850,
    areaUnit: "sq.ft.",
    status: "Featured",
    featured: true,
    yearBuilt: 2024,
    parking: "3 Covered Spaces",
    description: "Rising high above Bandra's prime coastal stretch, The Aria Penthouse features double-height glass walls, private rooftop jacuzzi deck, and bespoke Italian kitchen fittings.",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=1200&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?q=80&w=1200&auto=format&fit=crop"
    ],
    amenities: ["Sea View Terrace", "Rooftop Jacuzzi", "Private Elevator", "24/7 Butler Service", "Automated Blinds", "3-Car Underground Parking"],
    agentId: "agent-01"
  },
  {
    id: "prop-06",
    name: "Oak & Stone Residence",
    tagline: "Modernist villa blending natural teak timber and raw stone.",
    location: "Whitefield, Bengaluru",
    city: "Bengaluru",
    price: "₹4.65 Cr",
    priceValue: 46500000,
    type: "Villa",
    bedrooms: 4,
    bathrooms: 4,
    area: 4100,
    areaUnit: "sq.ft.",
    status: "For Sale",
    featured: false,
    yearBuilt: 2023,
    parking: "2 Covered Spaces",
    description: "Located within an exclusive gated enclave in Whitefield, Oak & Stone Residence features floor-to-ceiling glass opening onto a private koi pond garden and heated outdoor pool.",
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=1200&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop"
    ],
    amenities: ["Private Pool", "Koi Pond Garden", "Teak Wood Interiors", "Solar Heated Water", "Club House Access", "24/7 Guarded Security"],
    agentId: "agent-02"
  },
  {
    id: "prop-07",
    name: "The Regent",
    tagline: "Palatial 4-bedroom condominium on DLF Golf Course Road.",
    location: "Golf Course Road, Gurugram",
    city: "Delhi NCR",
    price: "₹6.80 Cr",
    priceValue: 68000000,
    type: "Apartment",
    bedrooms: 4,
    bathrooms: 5,
    area: 3900,
    areaUnit: "sq.ft.",
    status: "New Listing",
    featured: false,
    yearBuilt: 2024,
    parking: "3 Covered Spaces",
    description: "Overlooking the lush green greens of the golf course, The Regent offers expansive open-plan living, private elevators, VRF climate control, and triple-tier security.",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=1200&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?q=80&w=1200&auto=format&fit=crop"
    ],
    amenities: ["Golf Course View", "Olympic Pool", "Spa & Wellness Spa", "Concierge Desk", "Temperature Controlled Parking"],
    agentId: "agent-03"
  },
  {
    id: "prop-08",
    name: "Sea Glass Villa",
    tagline: "Clifftop Mediterranean oceanfront estate in Anjuna.",
    location: "North Goa, Goa",
    city: "Goa",
    price: "₹7.25 Cr",
    priceValue: 72500000,
    type: "Villa",
    bedrooms: 5,
    bathrooms: 6,
    area: 5200,
    areaUnit: "sq.ft.",
    status: "Featured",
    featured: true,
    yearBuilt: 2024,
    parking: "4 Spaces",
    description: "Perched atop the Anjuna cliffs with uninterrupted panoramic sunset views of the Arabian Sea. Sea Glass Villa features whitewashed stone walls, infinity pool, and private beach access path.",
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=1200&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?q=80&w=1200&auto=format&fit=crop"
    ],
    amenities: ["Sunset Sea View", "Infinity Pool", "Private Beach Access", "Outdoor BBQ Kitchen", "Staff Quarters"],
    agentId: "agent-01"
  },
  {
    id: "prop-09",
    name: "The Linden",
    tagline: "Bespoke heritage-modern apartment in central Kolkata.",
    location: "Park Street, Kolkata",
    city: "Kolkata",
    price: "₹1.95 Cr",
    priceValue: 19500000,
    type: "Apartment",
    bedrooms: 3,
    bathrooms: 3,
    area: 2100,
    areaUnit: "sq.ft.",
    status: "For Sale",
    featured: false,
    yearBuilt: 2022,
    parking: "1 Covered Space",
    description: "Situated in the heart of Park Street, The Linden blends high ceilings, Burmese teak flooring, and contemporary smart lighting systems for urban luxury lovers.",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop"
    ],
    amenities: ["High Ceilings", "Teak Flooring", "24/7 Security", "Elevator", "Central Location"],
    agentId: "agent-02"
  },
  {
    id: "prop-10",
    name: "Horizon House",
    tagline: "Contemporary estate with private tennis court and landscaped lawns.",
    location: "Alipore, Kolkata",
    city: "Kolkata",
    price: "₹6.35 Cr",
    priceValue: 63500000,
    type: "Villa",
    bedrooms: 4,
    bathrooms: 5,
    area: 4700,
    areaUnit: "sq.ft.",
    status: "For Sale",
    featured: false,
    yearBuilt: 2023,
    parking: "3 Spaces",
    description: "Horizon House is designed for serene family living in Alipore. Includes a private half tennis court, double-glazed soundproof windows, and expansive gardens.",
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=1200&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=1200&auto=format&fit=crop"
    ],
    amenities: ["Tennis Court", "Landscaped Garden", "Private Security", "Soundproof Windows", "Staff Quarters"],
    agentId: "agent-01"
  },
  {
    id: "prop-11",
    name: "Elysian Heights",
    tagline: "Ultra-prime 5-bedroom penthouse atop Sea Link in Worli.",
    location: "Worli, Mumbai",
    city: "Mumbai",
    price: "₹11.50 Cr",
    priceValue: 115000000,
    type: "Penthouse",
    bedrooms: 5,
    bathrooms: 6,
    area: 6100,
    areaUnit: "sq.ft.",
    status: "Featured",
    featured: true,
    yearBuilt: 2025,
    parking: "4 Covered Spaces",
    description: "Commanding 360-degree vistas of the Bandra-Worli Sea Link and Mumbai skyline. Elysian Heights is the pinnacle of luxury, featuring a private glass elevator and rooftop pool.",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=1200&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=1200&auto=format&fit=crop"
    ],
    amenities: ["360 Sea Views", "Private Glass Elevator", "Rooftop Pool", "Concierge Service", "4-Car Garage"],
    agentId: "agent-03"
  },
  {
    id: "prop-12",
    name: "The Courtyard Residence",
    tagline: "Serene courtyard villa with traditional South Indian stone motifs.",
    location: "Kalyan Nagar, Bengaluru",
    city: "Bengaluru",
    price: "₹3.10 Cr",
    priceValue: 31000000,
    type: "Villa",
    bedrooms: 3,
    bathrooms: 4,
    area: 3600,
    areaUnit: "sq.ft.",
    status: "New Listing",
    featured: false,
    yearBuilt: 2024,
    parking: "2 Spaces",
    description: "Built around a central open-to-sky rainwater courtyard with granite pillars, native foliage, and modern energy-efficient solar architecture.",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop"
    ],
    amenities: ["Open Courtyard", "Solar Power", "Granite Architecture", "Covered Garage", "Rainwater Harvesting"],
    agentId: "agent-02"
  }
];

const ADVISORS_DATA = [
  {
    id: "agent-01",
    name: "Ananya Kapoor",
    role: "Luxury Residential Specialist",
    experience: "8+ Years Experience",
    bio: "Ananya specializes in high-net-worth acquisitions across Kolkata & Mumbai's prime residential enclaves.",
    phone: "+91 98300 11223",
    email: "ananya@veloraestates.demo",
    image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=600&auto=format&fit=crop"
  },
  {
    id: "agent-02",
    name: "Rohan Mehta",
    role: "Property Advisor & Valuer",
    experience: "6+ Years Experience",
    bio: "Rohan brings a data-driven approach to luxury villa investments in Bengaluru and Goa coastal regions.",
    phone: "+91 98300 44556",
    email: "rohan@veloraestates.demo",
    image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=600&auto=format&fit=crop"
  },
  {
    id: "agent-03",
    name: "Ishita Sen",
    role: "Senior Investment Consultant",
    experience: "10+ Years Experience",
    bio: "Ishita advises NRIs and institutional family offices on trophy penthouse and oceanfront estate portfolios.",
    phone: "+91 98300 77889",
    email: "ishita@veloraestates.demo",
    image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=600&auto=format&fit=crop"
  }
];
