/**
 * VELORA ESTATES - Fictional Property Dataset (12 Properties)
 * Pure JavaScript Data Model - exclusive USD ($) pricing
 */

const PROPERTIES_DATA = [
  {
    id: "prop-01",
    name: "The Meridian Residence",
    tagline: "Ultra-luxury corner residence with panoramic city skyline views.",
    location: "Alipore, Kolkata",
    city: "Kolkata",
    price: "$3,850,000",
    priceValue: 3850000,
    type: "Apartment",
    bedrooms: 4,
    bathrooms: 4,
    area: 3240,
    areaUnit: "sq.ft.",
    status: "Featured",
    featured: true,
    yearBuilt: 2024,
    parking: "2 Covered Spaces",
    description: "The Meridian Residence stands as a benchmark of modern architectural excellence in Alipore. Designed around natural illumination and floor-to-ceiling glass, this 4-bedroom home offers double-height living rooms, imported Italian marble, and private elevator access.",
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=1200&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?q=80&w=1200&auto=format&fit=crop"
    ],
    amenities: ["Private Terrace", "Swimming Pool", "24/7 Security", "Fitness Center", "Covered Parking", "Smart Home Automation", "Concierge Service", "Landscaped Garden"],
    agentId: "agent-01"
  },
  {
    id: "prop-02",
    name: "The Aurelia House",
    tagline: "A private contemporary estate designed around light and landscape.",
    location: "Alipore, Kolkata",
    city: "Kolkata",
    price: "$8,750,000",
    priceValue: 8750000,
    type: "Villa",
    bedrooms: 5,
    bathrooms: 6,
    area: 5800,
    areaUnit: "sq.ft.",
    status: "Signature",
    featured: true,
    yearBuilt: 2025,
    parking: "4 Covered Spaces",
    description: "Aurelia House represents Velora's flagship residential villa in Kolkata's most prestigious enclave. Featuring a 50ft private infinity lap pool, internal glass courtyard, temperature-controlled wine room, and separate staff quarters.",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?q=80&w=1200&auto=format&fit=crop"
    ],
    amenities: ["Private Infinity Pool", "Internal Courtyard", "Wine Cellar", "Smart Home Automation", "Private Security Detail", "Home Theater", "4-Car Garage", "Staff Quarters"],
    agentId: "agent-01"
  },
  {
    id: "prop-03",
    name: "Solara Heights",
    tagline: "Sleek modern high-rise living near Rajarhat IT corridor.",
    location: "New Town, Kolkata",
    city: "Kolkata",
    price: "$2,150,000",
    priceValue: 2150000,
    type: "Apartment",
    bedrooms: 3,
    bathrooms: 3,
    area: 2450,
    areaUnit: "sq.ft.",
    status: "New Listing",
    featured: false,
    yearBuilt: 2023,
    parking: "2 Covered Spaces",
    description: "Solara Heights brings eco-conscious luxury to New Town Kolkata. Outfitted with VRV air conditioning, expansive wrap-around balconies, and access to a 20,000 sq.ft clubhouse.",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=1200&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600566752355-35792bedcfea?q=80&w=1200&auto=format&fit=crop"
    ],
    amenities: ["Rooftop Sky Lounge", "Clubhouse", "Swimming Pool", "24/7 Security", "Power Backup", "EV Charging Point"],
    agentId: "agent-02"
  },
  {
    id: "prop-04",
    name: "Casa Verde",
    tagline: "Tranquil Portuguese-style luxury sanctuary amidst coconut groves.",
    location: "North Goa, Goa",
    city: "Goa",
    price: "$5,400,000",
    priceValue: 5400000,
    type: "Villa",
    bedrooms: 4,
    bathrooms: 5,
    area: 4200,
    areaUnit: "sq.ft.",
    status: "Featured",
    featured: true,
    yearBuilt: 2024,
    parking: "3 Covered Spaces",
    description: "Casa Verde blends authentic Indo-Portuguese architectural heritage with ultra-modern Scandinavian interiors. Set across 1.2 acres of tropical gardens with direct riverfront access.",
    image: "https://images.unsplash.com/photo-1613977257363-707ba9348227?q=80&w=1200&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1613977257363-707ba9348227?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?q=80&w=1200&auto=format&fit=crop"
    ],
    amenities: ["Private River Deck", "Private Pool", "Heritage Architecture", "Solar Power Grid", "Staff Quarters", "Organic Kitchen Garden"],
    agentId: "agent-02"
  },
  {
    id: "prop-05",
    name: "The Horizon Penthouse",
    tagline: "Triplex penthouse boasting 360-degree ocean panoramas.",
    location: "Worli, Mumbai",
    city: "Mumbai",
    price: "$4,900,000",
    priceValue: 4900000,
    type: "Penthouse",
    bedrooms: 4,
    bathrooms: 5,
    area: 4600,
    areaUnit: "sq.ft.",
    status: "Signature",
    featured: true,
    yearBuilt: 2025,
    parking: "3 Covered Spaces",
    description: "Crown jewel of Worli's skyline, this triplex penthouse features a private rooftop plunge pool, floor-to-ceiling glass wraps, motorized solar shades, and private car-lift access directly to your foyer.",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=1200&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=1200&auto=format&fit=crop"
    ],
    amenities: ["Private Rooftop Pool", "Car-Lift Access", "360 Ocean Views", "Private Elevator", "Wine Vault", "Concierge Service"],
    agentId: "agent-01"
  },
  {
    id: "prop-06",
    name: "Sereno Villa",
    tagline: "Contemporary sanctuary in Bengaluru's tech-elite enclave.",
    location: "Indiranagar, Bengaluru",
    city: "Bengaluru",
    price: "$1,950,000",
    priceValue: 1950000,
    type: "Villa",
    bedrooms: 4,
    bathrooms: 4,
    area: 3800,
    areaUnit: "sq.ft.",
    status: "New Listing",
    featured: false,
    yearBuilt: 2024,
    parking: "2 Covered Spaces",
    description: "Sereno Villa offers quiet architectural sophistication tucked inside Indiranagar. Features double-height glass facades, zero-carbon construction, and a heated rooftop pool.",
    image: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?q=80&w=1200&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop"
    ],
    amenities: ["Heated Rooftop Pool", "Smart Home Automation", "Solar Roof Tiles", "Private Garden", "Italian Kitchen"],
    agentId: "agent-02"
  },
  {
    id: "prop-07",
    name: "The Oberoi Estate",
    tagline: "Sprawling private estate with lush private grounds and tennis court.",
    location: "Golf Course Road, Gurgaon",
    city: "Delhi NCR",
    price: "$6,200,000",
    priceValue: 6200000,
    type: "Villa",
    bedrooms: 6,
    bathrooms: 7,
    area: 7200,
    areaUnit: "sq.ft.",
    status: "Signature",
    featured: true,
    yearBuilt: 2025,
    parking: "5 Covered Spaces",
    description: "Designed for distinguished entertaining, The Oberoi Estate features a private championship tennis court, temperature-controlled indoor pool, and private guest villa.",
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=1200&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=1200&auto=format&fit=crop"
    ],
    amenities: ["Private Tennis Court", "Indoor Heated Pool", "Guest House", "5-Car Garage", "Helipad Access", "24/7 Armed Security"],
    agentId: "agent-03"
  },
  {
    id: "prop-08",
    name: "Vanguard Sky Residence",
    tagline: "Minimalist glass duplex overlooking South Mumbai harbor.",
    location: "Bandra West, Mumbai",
    city: "Mumbai",
    price: "$3,100,000",
    priceValue: 3100000,
    type: "Apartment",
    bedrooms: 3,
    bathrooms: 4,
    area: 3100,
    areaUnit: "sq.ft.",
    status: "Featured",
    featured: true,
    yearBuilt: 2024,
    parking: "2 Covered Spaces",
    description: "Located in Bandra West's premier avenue, Vanguard Sky Residence combines clean architectural lines with customized bronze metal cladding and private harbor views.",
    image: "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?q=80&w=1200&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?q=80&w=1200&auto=format&fit=crop"
    ],
    amenities: ["Harbor View Balcony", "Private Elevator", "Valet Parking", "Infrared Sauna", "24/7 Security"],
    agentId: "agent-01"
  },
  {
    id: "prop-09",
    name: "The Regency Manor",
    tagline: "Iconic trophy palace set across 2 acres of manicured lawn.",
    location: "Lutyens, Delhi",
    city: "Delhi NCR",
    price: "$11,500,000",
    priceValue: 11500000,
    type: "Villa",
    bedrooms: 7,
    bathrooms: 8,
    area: 9500,
    areaUnit: "sq.ft.",
    status: "Signature",
    featured: true,
    yearBuilt: 2025,
    parking: "6 Covered Spaces",
    description: "An extraordinary trophy property in Lutyens Delhi. Features classical neo-colonial architecture, private ballroom, heated olympic pool, and subterranean spa facility.",
    image: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?q=80&w=1200&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?q=80&w=1200&auto=format&fit=crop"
    ],
    amenities: ["Private Ballroom", "Subterranean Spa", "Olympic Pool", "6-Car Underground Garage", "Embassy Security Protocol"],
    agentId: "agent-03"
  },
  {
    id: "prop-10",
    name: "Aura Residence",
    tagline: "Refined minimalist home overlooking East Kolkata wetlands.",
    location: "EM Bypass, Kolkata",
    city: "Kolkata",
    price: "$2,800,000",
    priceValue: 2800000,
    type: "Apartment",
    bedrooms: 4,
    bathrooms: 4,
    area: 3400,
    areaUnit: "sq.ft.",
    status: "New Listing",
    featured: false,
    yearBuilt: 2024,
    parking: "2 Covered Spaces",
    description: "Aura Residence blends zen design philosophy with modern structural technology. Floor-to-ceiling glass facades showcase tranquil sunrise views across the nature reserve.",
    image: "https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?q=80&w=1200&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?q=80&w=1200&auto=format&fit=crop"
    ],
    amenities: ["Nature Reserve Views", "Zen Courtyard", "Infinity Edge Pool", "24/7 Security", "Private Lounge"],
    agentId: "agent-01"
  },
  {
    id: "prop-11",
    name: "Azura Coastal Villa",
    tagline: "Beachfront sanctuary with private access to white sands.",
    location: "Anjuna, Goa",
    city: "Goa",
    price: "$7,100,000",
    priceValue: 7100000,
    type: "Villa",
    bedrooms: 5,
    bathrooms: 6,
    area: 5100,
    areaUnit: "sq.ft.",
    status: "Signature",
    featured: true,
    yearBuilt: 2025,
    parking: "3 Covered Spaces",
    description: "Step directly onto the sands of Anjuna Beach from your private deck. Azura Villa features teakwood deckings, private infinity ocean pool, and outdoor gourmet kitchen.",
    image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?q=80&w=1200&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?q=80&w=1200&auto=format&fit=crop"
    ],
    amenities: ["Direct Beach Access", "Private Infinity Pool", "Outdoor Gourmet Kitchen", "Solar Power Grid", "CCTV Security"],
    agentId: "agent-02"
  },
  {
    id: "prop-12",
    name: "Lumina Penthouse",
    tagline: "Chic modern penthouse overlooking Bengaluru central park.",
    location: "Koramangala, Bengaluru",
    city: "Bengaluru",
    price: "$1,650,000",
    priceValue: 1650000,
    type: "Penthouse",
    bedrooms: 3,
    bathrooms: 3,
    area: 2800,
    areaUnit: "sq.ft.",
    status: "New Listing",
    featured: false,
    yearBuilt: 2023,
    parking: "2 Covered Spaces",
    description: "Lumina Penthouse offers urban penthouse sophistication with private rooftop jacuzzi, glass observatory ceiling, and automated climate control.",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=1200&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=1200&auto=format&fit=crop"
    ],
    amenities: ["Private Rooftop Jacuzzi", "Glass Observatory", "Smart Home Automation", "24/7 Security"],
    agentId: "agent-02"
  }
];

const ADVISORS_DATA = [
  {
    id: "agent-01",
    name: "Ananya Kapoor",
    role: "Luxury Residential Specialist",
    experience: "8+ Years Experience",
    image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=600&auto=format&fit=crop"
  },
  {
    id: "agent-02",
    name: "Rohan Mehta",
    role: "Property Advisor & Valuer",
    experience: "6+ Years Experience",
    image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=600&auto=format&fit=crop"
  },
  {
    id: "agent-03",
    name: "Ishita Sen",
    role: "Senior Investment Consultant",
    experience: "10+ Years Experience",
    image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=600&auto=format&fit=crop"
  }
];
